name: raahi_server
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  chopper: ^2.0.0
  provider:
  built_value: ^7.1.0
  polyline: ^1.0.2
  sms_maintained:
  get_it:
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  chopper_generator: ^2.0.0
  built_value_generator:

flutter:
  uses-material-design: true
